"""Add DailyAccountSummary and SystemSummary models

Revision ID: 44dac119c9f6
Revises: 5a6555b72d0a
Create Date: 2025-05-30 17:34:24.092491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44dac119c9f6'
down_revision = '5a6555b72d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('balance')
        batch_op.drop_column('passphrase')

    with op.batch_alter_table('system_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_strategies', sa.Integer(), nullable=False))
        batch_op.drop_column('total_accounts')

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('executed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('system_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_accounts', sa.INTEGER(), nullable=False))
        batch_op.drop_column('active_strategies')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passphrase', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('balance', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=False))

    # ### end Alembic commands ###
