"""No changes needed - models already match database

Revision ID: 5a6555b72d0a
Revises: bc1e2f946180
Create Date: 2025-05-30 16:59:49.143305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a6555b72d0a'
down_revision = 'bc1e2f946180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_accounts')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=False))
        batch_op.drop_column('account_name')

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executed_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('telegram_id')

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('executed_at')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('balance')

    op.create_table('_alembic_tmp_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=50), nullable=False),
    sa.Column('api_key', sa.TEXT(), nullable=False),
    sa.Column('public_api', sa.TEXT(), nullable=False),
    sa.Column('secret_api', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('balance', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
