"""Remove api_key field from Account model

Revision ID: b7a9b53c46b4
Revises: f3259e921bf6
Create Date: 2025-05-31 14:32:28.548114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a9b53c46b4'
down_revision = 'f3259e921bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
