"""Add max_symbols to StrategyAccount

Revision ID: eb67ce74e0a3
Revises: 44dac119c9f6
Create Date: 2025-05-31 12:31:00.284124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb67ce74e0a3'
down_revision = '44dac119c9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_symbols', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_accounts', schema=None) as batch_op:
        batch_op.drop_column('max_symbols')

    # ### end Alembic commands ###
